In [1]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

import numpy as np
import matplotlib.pyplot as plt
from helpers import load_csv_data

In [2]:
x_train, x_test, y_train, train_ids, test_ids=load_csv_data(data_path='../dataset')

In [3]:
train_ids

array([     0,      1,      2, ..., 328132, 328133, 328134],
      shape=(328135,))

In [4]:
test_ids

array([328135, 328136, 328137, ..., 437511, 437512, 437513],
      shape=(109379,))

In [5]:
x_train.shape

(328135, 321)

In [6]:
y_train.shape

(328135,)

In [7]:
np.set_printoptions(suppress=True, precision=2)

In [8]:
print("X train:", x_train.shape)
print("y train:", y_train.shape)

print("Number of NaNs:", np.isnan(x_train).sum())
print("NaN ratio:", np.isnan(x_train).mean())

X train: (328135, 321)
y train: (328135,)
Number of NaNs: 47175779
NaN ratio: 0.4478798165806975


In [9]:
values, counts = np.unique(y_train, return_counts=True)

print(values)
print(counts)
print(counts / len(y_train))

[-1  1]
[299160  28975]
[0.91 0.09]


In [10]:
missing_ratio = np.isnan(x_train).mean(axis=0)

In [11]:
high_miss_feature=missing_ratio[missing_ratio>0.5]
high_miss_feature.shape



(147,)

In [12]:
print(np.min(missing_ratio))
print(np.max(missing_ratio))
print(np.median(missing_ratio))

0.0
0.9999024791625398
0.35764243375439986


In [13]:
unique_counts = []

for j in range(x_train.shape[1]):
    column = x_train[:, j]
    column_without_nan = column[~np.isnan(column)]
    unique_counts.append(np.unique(column_without_nan).size)

In [14]:
x_train[:,0]

array([53., 33., 20., ..., 39., 33., 32.], shape=(328135,))

In [15]:
feature_name=np.genfromtxt('../dataset/x_train.csv',delimiter=',',dtype=str,max_rows=1)
print(feature_name)
print(feature_name.shape)

['Id' '_STATE' 'FMONTH' 'IDATE' 'IMONTH' 'IDAY' 'IYEAR' 'DISPCODE' 'SEQNO'
 '_PSU' 'CTELENUM' 'PVTRESD1' 'COLGHOUS' 'STATERES' 'CELLFON3' 'LADULT'
 'NUMADULT' 'NUMMEN' 'NUMWOMEN' 'CTELNUM1' 'CELLFON2' 'CADULT' 'PVTRESD2'
 'CCLGHOUS' 'CSTATE' 'LANDLINE' 'HHADULT' 'GENHLTH' 'PHYSHLTH' 'MENTHLTH'
 'POORHLTH' 'HLTHPLN1' 'PERSDOC2' 'MEDCOST' 'CHECKUP1' 'BPHIGH4' 'BPMEDS'
 'BLOODCHO' 'CHOLCHK' 'TOLDHI2' 'CVDSTRK3' 'ASTHMA3' 'ASTHNOW' 'CHCSCNCR'
 'CHCOCNCR' 'CHCCOPD1' 'HAVARTH3' 'ADDEPEV2' 'CHCKIDNY' 'DIABETE3'
 'DIABAGE2' 'SEX' 'MARITAL' 'EDUCA' 'RENTHOM1' 'NUMHHOL2' 'NUMPHON2'
 'CPDEMO1' 'VETERAN3' 'EMPLOY1' 'CHILDREN' 'INCOME2' 'INTERNET' 'WEIGHT2'
 'HEIGHT3' 'PREGNANT' 'QLACTLM2' 'USEEQUIP' 'BLIND' 'DECIDE' 'DIFFWALK'
 'DIFFDRES' 'DIFFALON' 'SMOKE100' 'SMOKDAY2' 'STOPSMK2' 'LASTSMK2'
 'USENOW3' 'ALCDAY5' 'AVEDRNK2' 'DRNK3GE5' 'MAXDRNKS' 'FRUITJU1' 'FRUIT1'
 'FVBEANS' 'FVGREEN' 'FVORANG' 'VEGETAB1' 'EXERANY2' 'EXRACT11' 'EXEROFT1'
 'EXERHMM1' 'EXRACT21' 'EXEROFT2' 'EXERHMM2' 'STRENGTH' 'LM

In [16]:
feature_names=feature_name[1:]
print(feature_names)

['_STATE' 'FMONTH' 'IDATE' 'IMONTH' 'IDAY' 'IYEAR' 'DISPCODE' 'SEQNO'
 '_PSU' 'CTELENUM' 'PVTRESD1' 'COLGHOUS' 'STATERES' 'CELLFON3' 'LADULT'
 'NUMADULT' 'NUMMEN' 'NUMWOMEN' 'CTELNUM1' 'CELLFON2' 'CADULT' 'PVTRESD2'
 'CCLGHOUS' 'CSTATE' 'LANDLINE' 'HHADULT' 'GENHLTH' 'PHYSHLTH' 'MENTHLTH'
 'POORHLTH' 'HLTHPLN1' 'PERSDOC2' 'MEDCOST' 'CHECKUP1' 'BPHIGH4' 'BPMEDS'
 'BLOODCHO' 'CHOLCHK' 'TOLDHI2' 'CVDSTRK3' 'ASTHMA3' 'ASTHNOW' 'CHCSCNCR'
 'CHCOCNCR' 'CHCCOPD1' 'HAVARTH3' 'ADDEPEV2' 'CHCKIDNY' 'DIABETE3'
 'DIABAGE2' 'SEX' 'MARITAL' 'EDUCA' 'RENTHOM1' 'NUMHHOL2' 'NUMPHON2'
 'CPDEMO1' 'VETERAN3' 'EMPLOY1' 'CHILDREN' 'INCOME2' 'INTERNET' 'WEIGHT2'
 'HEIGHT3' 'PREGNANT' 'QLACTLM2' 'USEEQUIP' 'BLIND' 'DECIDE' 'DIFFWALK'
 'DIFFDRES' 'DIFFALON' 'SMOKE100' 'SMOKDAY2' 'STOPSMK2' 'LASTSMK2'
 'USENOW3' 'ALCDAY5' 'AVEDRNK2' 'DRNK3GE5' 'MAXDRNKS' 'FRUITJU1' 'FRUIT1'
 'FVBEANS' 'FVGREEN' 'FVORANG' 'VEGETAB1' 'EXERANY2' 'EXRACT11' 'EXEROFT1'
 'EXERHMM1' 'EXRACT21' 'EXEROFT2' 'EXERHMM2' 'STRENGTH' 'LMTJOIN

In [17]:
unique_count_dict = dict(zip(feature_names, unique_counts))

In [18]:
unique_count_dict

{np.str_('_STATE'): 53,
 np.str_('FMONTH'): 12,
 np.str_('IDATE'): 414,
 np.str_('IMONTH'): 12,
 np.str_('IDAY'): 31,
 np.str_('IYEAR'): 2,
 np.str_('DISPCODE'): 2,
 np.str_('SEQNO'): 21780,
 np.str_('_PSU'): 21780,
 np.str_('CTELENUM'): 1,
 np.str_('PVTRESD1'): 2,
 np.str_('COLGHOUS'): 1,
 np.str_('STATERES'): 1,
 np.str_('CELLFON3'): 2,
 np.str_('LADULT'): 2,
 np.str_('NUMADULT'): 16,
 np.str_('NUMMEN'): 12,
 np.str_('NUMWOMEN'): 11,
 np.str_('CTELNUM1'): 1,
 np.str_('CELLFON2'): 1,
 np.str_('CADULT'): 2,
 np.str_('PVTRESD2'): 2,
 np.str_('CCLGHOUS'): 1,
 np.str_('CSTATE'): 2,
 np.str_('LANDLINE'): 4,
 np.str_('HHADULT'): 25,
 np.str_('GENHLTH'): 7,
 np.str_('PHYSHLTH'): 33,
 np.str_('MENTHLTH'): 33,
 np.str_('POORHLTH'): 33,
 np.str_('HLTHPLN1'): 4,
 np.str_('PERSDOC2'): 5,
 np.str_('MEDCOST'): 4,
 np.str_('CHECKUP1'): 7,
 np.str_('BPHIGH4'): 6,
 np.str_('BPMEDS'): 4,
 np.str_('BLOODCHO'): 4,
 np.str_('CHOLCHK'): 6,
 np.str_('TOLDHI2'): 4,
 np.str_('CVDSTRK3'): 4,
 np.str_('ASTHMA3'

In [19]:
health_idx=np.where(y_train==-1)[0]
unhealth_idx=np.where(y_train==1)[0]
health_idx

array([     0,      1,      2, ..., 328132, 328133, 328134],
      shape=(299160,))

In [20]:
unique_counts

[53,
 12,
 414,
 12,
 31,
 2,
 2,
 21780,
 21780,
 1,
 2,
 1,
 1,
 2,
 2,
 16,
 12,
 11,
 1,
 1,
 2,
 2,
 1,
 2,
 4,
 25,
 7,
 33,
 33,
 33,
 4,
 5,
 4,
 7,
 6,
 4,
 4,
 6,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 6,
 98,
 2,
 7,
 7,
 5,
 4,
 8,
 4,
 4,
 9,
 25,
 10,
 4,
 550,
 142,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 4,
 10,
 5,
 40,
 48,
 43,
 58,
 109,
 134,
 108,
 115,
 103,
 133,
 4,
 77,
 115,
 194,
 78,
 99,
 168,
 101,
 4,
 4,
 5,
 13,
 8,
 4,
 28,
 13,
 4,
 4,
 412,
 11,
 4,
 5,
 3,
 79,
 72,
 47,
 41,
 45,
 7,
 4,
 4,
 5,
 17,
 7,
 6,
 15,
 4,
 4,
 8,
 4,
 8,
 7,
 7,
 10,
 8,
 4,
 4,
 3,
 3,
 4,
 7,
 7,
 7,
 7,
 4,
 4,
 136,
 4,
 72,
 3,
 8,
 11,
 18,
 25,
 8,
 7,
 6,
 9,
 4,
 4,
 4,
 5,
 4,
 3,
 4,
 6,
 4,
 4,
 4,
 6,
 5,
 5,
 4,
 4,
 7,
 4,
 7,
 4,
 7,
 4,
 4,
 7,
 4,
 7,
 4,
 4,
 8,
 4,
 4,
 4,
 4,
 7,
 7,
 5,
 8,
 8,
 8,
 6,
 93,
 6,
 92,
 6,
 6,
 3,
 8,
 4,
 4,
 7,
 6,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 4,
 4,
 8,
 3,
 4,
 1306,
 1304,
 12,
 5528,
 3,
 9,
 9,


In [21]:
unique_counts=np.array(unique_counts)
one_value=np.where(unique_counts==1)[0]
few_value=np.where((2<=unique_counts)&(unique_counts<=50))[0]
many_value=np.where(50<unique_counts)[0]


In [22]:
feature_names[one_value]

array(['CTELENUM', 'COLGHOUS', 'STATERES', 'CTELNUM1', 'CELLFON2',
       'CCLGHOUS'], dtype='<U8')

In [23]:
x_train[:,one_value]

array([[nan, nan, nan,  1.,  1., nan],
       [ 1., nan,  1., nan, nan, nan],
       [ 1., nan,  1., nan, nan, nan],
       ...,
       [ 1., nan,  1., nan, nan, nan],
       [ 1., nan,  1., nan, nan, nan],
       [ 1., nan,  1., nan, nan, nan]], shape=(328135, 6))

In [24]:
a={}
for i in one_value:
    target_values=x_train[:,i]
    missing_mask=np.isnan(target_values)
    observed_mask=~missing_mask
    miss_y=y_train[missing_mask]
    normal_y=y_train[observed_mask]
    missing_positive_rate = (miss_y == 1).mean()
    observed_positive_rate = (normal_y == 1).mean()
    
    
    a[feature_names[i]]={"missing_count":len(miss_y),"missing_positive_rate": missing_positive_rate,
                         "observed_count":len(normal_y),"observed_positive_rate": observed_positive_rate}

a
    

{np.str_('CTELENUM'): {'missing_count': 139415,
  'missing_positive_rate': np.float64(0.06233905964207582),
  'observed_count': 188720,
  'observed_positive_rate': np.float64(0.10748198389147944)},
 np.str_('COLGHOUS'): {'missing_count': 328103,
  'missing_positive_rate': np.float64(0.08829544380880394),
  'observed_count': 32,
  'observed_positive_rate': np.float64(0.15625)},
 np.str_('STATERES'): {'missing_count': 139416,
  'missing_positive_rate': np.float64(0.06233861249784817),
  'observed_count': 188719,
  'observed_positive_rate': np.float64(0.10748255342599314)},
 np.str_('CTELNUM1'): {'missing_count': 188720,
  'missing_positive_rate': np.float64(0.10748198389147944),
  'observed_count': 139415,
  'observed_positive_rate': np.float64(0.06233905964207582)},
 np.str_('CELLFON2'): {'missing_count': 188720,
  'missing_positive_rate': np.float64(0.10748198389147944),
  'observed_count': 139415,
  'observed_positive_rate': np.float64(0.06233905964207582)},
 np.str_('CCLGHOUS'): {'mi

The gap between nan and 1 are not huge. We could ignore these feature at first.

In [25]:
feature_names[few_value]

array(['FMONTH', 'IMONTH', 'IDAY', 'IYEAR', 'DISPCODE', 'PVTRESD1',
       'CELLFON3', 'LADULT', 'NUMADULT', 'NUMMEN', 'NUMWOMEN', 'CADULT',
       'PVTRESD2', 'CSTATE', 'LANDLINE', 'HHADULT', 'GENHLTH', 'PHYSHLTH',
       'MENTHLTH', 'POORHLTH', 'HLTHPLN1', 'PERSDOC2', 'MEDCOST',
       'CHECKUP1', 'BPHIGH4', 'BPMEDS', 'BLOODCHO', 'CHOLCHK', 'TOLDHI2',
       'CVDSTRK3', 'ASTHMA3', 'ASTHNOW', 'CHCSCNCR', 'CHCOCNCR',
       'CHCCOPD1', 'HAVARTH3', 'ADDEPEV2', 'CHCKIDNY', 'DIABETE3', 'SEX',
       'MARITAL', 'EDUCA', 'RENTHOM1', 'NUMHHOL2', 'NUMPHON2', 'CPDEMO1',
       'VETERAN3', 'EMPLOY1', 'CHILDREN', 'INCOME2', 'INTERNET',
       'PREGNANT', 'QLACTLM2', 'USEEQUIP', 'BLIND', 'DECIDE', 'DIFFWALK',
       'DIFFDRES', 'DIFFALON', 'SMOKE100', 'SMOKDAY2', 'STOPSMK2',
       'LASTSMK2', 'USENOW3', 'ALCDAY5', 'AVEDRNK2', 'DRNK3GE5',
       'EXERANY2', 'LMTJOIN3', 'ARTHDIS2', 'ARTHSOCL', 'JOINPAIN',
       'SEATBELT', 'FLUSHOT6', 'FLSHTMY2', 'IMFVPLAC', 'PNEUVAC3',
       'HIVTST6', 'WHRTST1

In [26]:
for i in few_value:
    column = x_train[:, i]
    values, counts = np.unique(column[~np.isnan(column)], return_counts=True)
    positive_rates=[]
    for value in values:
        mask=(column==value)
        postive_raito=(y_train[mask]==1).mean()
        positive_rates.append(postive_raito)

    missing_mask=np.isnan(column)
    missing_positive_rate=(y_train[missing_mask]==1).mean()
    missing_ratio = missing_mask.mean()
    


    print(feature_names[i])
    print(values)
    print(counts)
    print(positive_rates)
    print(missing_ratio)
    print("missing positive rate:", missing_positive_rate)
    

C:\Users\shu\AppData\Local\Temp\ipykernel_29444\3292204488.py:11: RuntimeWarning: Mean of empty slice.
  missing_positive_rate=(y_train[missing_mask]==1).mean()
c:\Users\shu\miniconda3\envs\ml-study\lib\site-packages\numpy\_core\_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


FMONTH
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[32926 27550 25980 30272 25002 24618 30716 24482 24787 31335 25512 24955]
[np.float64(0.08604142622851242), np.float64(0.08511796733212341), np.float64(0.0890685142417244), np.float64(0.0846656976744186), np.float64(0.08787297016238702), np.float64(0.08916240149484117), np.float64(0.08659981768459435), np.float64(0.09141410015521607), np.float64(0.09125751401944568), np.float64(0.08450614329025052), np.float64(0.09442615239887112), np.float64(0.09260669204568223)]
0.0
missing positive rate: nan
IMONTH
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[27937 29161 31444 26611 25675 26894 27512 26873 22925 26443 29486 27174]
[np.float64(0.08580019329204996), np.float64(0.08387915366414046), np.float64(0.0873298562523852), np.float64(0.087257149299162), np.float64(0.0888412852969815), np.float64(0.08723135271807839), np.float64(0.08927013666763595), np.float64(0.09001600119078629), np.float64(0.09164667393675027), np.float64(0.09019

In [27]:
numeric_names = [
    "NUMADULT",
    "NUMMEN",
    "NUMWOMEN",
    "HHADULT",
    "PHYSHLTH",
    "MENTHLTH",
    "POORHLTH",
    "NUMPHON2",
    "CHILDREN",
    "AVEDRNK2",
    "DRNK3GE5",
    "JOINPAIN",
    "DOCTDIAB",
    "CHKHEMO3",
    "FEETCHK",
    "ASERVIST",
    "ASDRVIST",
    "ASRCHKUP",
    "ADPLEASR",
    "ADDOWN",
    "ADSLEEP",
    "ADENERGY",
    "ADEAT1",
    "ADFAIL",
    "ADTHINK",
    "ADMOVE",
    "METVL11_",
    "METVL21_",
]

ordinal_names = [
    "GENHLTH",
    "CHECKUP1",
    "CHOLCHK",
    "EDUCA",
    "INCOME2",
    "SMOKDAY2",
    "LASTSMK2",
    "ARTHSOCL",
    "SEATBELT",
    "CRGVLNG1",
    "CRGVHRS1",
    "ARTTODAY",
    "HOWLONG",
    "LASTPAP2",
    "HPLSTTST",
    "LENGEXAM",
    "LSTBLDS3",
    "LASTSIG3",
    "PSATIME",
    "SCNTMNY1",
    "SCNTMEL1",
    "EMTSUPRT",
    "LSATISFY",
    "_AGEG5YR",
    "_AGE65YR",
    "_AGE_G",
    "_BMI5CAT",
    "_CHLDCNT",
    "_EDUCAG",
    "_INCOMG",
    "_SMOKER3",
    "_PACAT1",
    "_PAREC1",
    "_LMTACT1",
    "_LMTWRK1",
    "_LMTSCL1",
]

categorical_names = [
    "HLTHPLN1",
    "PERSDOC2",
    "MEDCOST",
    "BPHIGH4",
    "BPMEDS",
    "BLOODCHO",
    "TOLDHI2",
    "CVDSTRK3",
    "ASTHMA3",
    "ASTHNOW",
    "CHCSCNCR",
    "CHCOCNCR",
    "CHCCOPD1",
    "HAVARTH3",
    "ADDEPEV2",
    "CHCKIDNY",
    "DIABETE3",
    "SEX",
    "MARITAL",
    "RENTHOM1",
    "VETERAN3",
    "EMPLOY1",
    "INTERNET",
    "PREGNANT",
    "QLACTLM2",
    "USEEQUIP",
    "BLIND",
    "DECIDE",
    "DIFFWALK",
    "DIFFDRES",
    "DIFFALON",
    "SMOKE100",
    "STOPSMK2",
    "USENOW3",
    "EXERANY2",
    "LMTJOIN3",
    "ARTHDIS2",
    "FLUSHOT6",
    "IMFVPLAC",
    "PNEUVAC3",
    "HIVTST6",
    "WHRTST10",
    "PDIABTST",
    "PREDIAB1",
    "INSULIN",
    "EYEEXAM",
    "DIABEYE",
    "DIABEDU",
    "CAREGIV1",
    "CRGVREL1",
    "CRGVPRB1",
    "CRGVPERS",
    "CRGVHOUS",
    "CRGVMST2",
    "CRGVEXPT",
    "VIDFCLT2",
    "VIREDIF3",
    "VIPRFVS2",
    "VINOCRE2",
    "VIEYEXM2",
    "VIINSUR2",
    "VICTRCT4",
    "VIGLUMA2",
    "VIMACDG2",
    "CIMEMLOS",
    "CDHOUSE",
    "CDASSIST",
    "CDHELP",
    "CDSOCIAL",
    "CDDISCUS",
    "WTCHSALT",
    "DRADVISE",
    "ASATTACK",
    "ASYMPTOM",
    "ASNOSLEP",
    "ASTHMED3",
    "ASINHALR",
    "HAREHAB1",
    "STREHAB1",
    "CVDASPRN",
    "ASPUNSAF",
    "RLIVPAIN",
    "RDUCHART",
    "RDUCSTRK",
    "ARTHWGT",
    "ARTHEXER",
    "ARTHEDU",
    "TETANUS",
    "HPVADVC2",
    "SHINGLE2",
    "HADMAM",
    "HADPAP2",
    "HPVTEST",
    "HADHYST2",
    "PROFEXAM",
    "BLDSTOOL",
    "HADSIGM3",
    "HADSGCO1",
    "PCPSAAD2",
    "PCPSADI1",
    "PCPSARE1",
    "PSATEST1",
    "PCPSARS1",
    "PCPSADE1",
    "PCDMDECN",
    "SCNTPAID",
    "SCNTLPAD",
    "SXORIENT",
    "TRNSGNDR",
    "RCSGENDR",
    "RCSRLTN2",
    "CASTHDX2",
    "CASTHNO2",
    "MISTMNT",
    "ADANXEV",
    "QSTLANG",
    "MSCODE",
    "_CHISPNC",
    "_CRACE1",
    "_CPRACE",
    "_RFHLTH",
    "_HCVU651",
    "_RFHYPE5",
    "_CHOLCHK",
    "_RFCHOL",
    "_LTASTH1",
    "_CASTHM1",
    "_ASTHMS1",
    "_DRDXAR1",
    "_PRACE1",
    "_MRACE1",
    "_HISPANC",
    "_RACE",
    "_RACEG21",
    "_RACEGR3",
    "_RACE_G1",
    "_RFBMI5",
    "_RFSMOK3",
    "DRNKANY5",
    "_RFBING5",
    "_RFDRHV5",
    "_MISFRTN",
    "_MISVEGN",
    "_FRTRESP",
    "_VEGRESP",
    "_FRTLT1",
    "_VEGLT1",
    "_FRT16",
    "_VEG23",
    "_FRUITEX",
    "_VEGETEX",
    "_TOTINDA",
    "ACTIN11_",
    "ACTIN21_",
    "PAMISS1_",
    "_PAINDX1",
    "_PA150R2",
    "_PA300R2",
    "_PA30021",
    "_PASTRNG",
    "_PASTAE1",
    "_RFSEAT2",
    "_RFSEAT3",
    "_FLSHOT6",
    "_PNEUMO2",
    "_AIDTST3",
]

encoded_numeric_names = [
    "ALCDAY5",
    "FLSHTMY2",
    "ASACTLIM",
    "HPVADSHT",
    "DROCDY3_",
]

survey_admin_names = [
    "FMONTH",
    "IMONTH",
    "IDAY",
    "IYEAR",
    "DISPCODE",
    "PVTRESD1",
    "CELLFON3",
    "LADULT",
    "CADULT",
    "PVTRESD2",
    "CSTATE",
    "LANDLINE",
    "NUMHHOL2",
    "CPDEMO1",
    "QSTVER",
    "_RAWRAKE",
    "_DUALUSE",
]

In [28]:
name_to_idx = {
    name: i
    for i, name in enumerate(feature_names)
}

In [29]:
onevalue_idx=one_value

In [30]:
numeric_idx = np.array([
    name_to_idx[name]
    for name in numeric_names
])

ordinal_idx = np.array([
    name_to_idx[name]
    for name in ordinal_names
])

categorical_idx = np.array([
    name_to_idx[name]
    for name in categorical_names
])

encoded_numeric_idx = np.array([
    name_to_idx[name]
    for name in encoded_numeric_names
])

survey_admin_idx = np.array([
    name_to_idx[name]
    for name in survey_admin_names
])

In [31]:
classified_idx = np.concatenate([
    numeric_idx,
    ordinal_idx,
    categorical_idx,
    encoded_numeric_idx,
    survey_admin_idx
])

unclassified_idx = np.setdiff1d(
    few_value,
    classified_idx
)

feature_names[unclassified_idx]

array([], dtype='<U8')

In [32]:
len(classified_idx), len(np.unique(classified_idx))

(252, 252)

Imputation 

In [33]:
def transform_one_value(x, onevalue_idx):
    x_one = x[:, onevalue_idx].copy()
    x_one[np.isnan(x_one)] = -1
    return x_one

In [34]:
x_one=transform_one_value(x_train,onevalue_idx=onevalue_idx)
print(np.unique(x_one))
print(np.isnan(x_one).any())
print(x_one.shape)

[-1.  1.]
False
(328135, 6)


In [35]:
numeric_rules = {
    # days in past 30 days
    "PHYSHLTH": {
        "zero_codes": [88],
        "nan_codes": [77, 99],
    },
    "MENTHLTH": {
        "zero_codes": [88],
        "nan_codes": [77, 99],
    },
    "POORHLTH": {
        "zero_codes": [88],
        "nan_codes": [77, 99],
    },

    # household counts
    "HHADULT": {
        "zero_codes": [],
        "nan_codes": [77, 99],
    },

    # phone count
    "NUMPHON2": {
        "zero_codes": [],
        "nan_codes": [7, 9],
    },

    # children
    "CHILDREN": {
        "zero_codes": [88],
        "nan_codes": [99],
    },

    # alcohol
    "AVEDRNK2": {
        "zero_codes": [],
        "nan_codes": [77, 99],
    },
    "DRNK3GE5": {
        "zero_codes": [88],
        "nan_codes": [77, 99],
    },

    # pain
    "JOINPAIN": {
        "zero_codes": [],
        "nan_codes": [77, 99],
    },

    # diabetes-related counts
    "DOCTDIAB": {
        "zero_codes": [88],
        "nan_codes": [77, 99],
    },
    "CHKHEMO3": {
        "zero_codes": [88],
        "nan_codes": [77, 98, 99],
    },
    "FEETCHK": {
        "zero_codes": [88],
        "nan_codes": [77, 99],
    },

    # asthma-related visit counts
    "ASERVIST": {
        "zero_codes": [88],
        "nan_codes": [98],
    },
    "ASDRVIST": {
        "zero_codes": [88],
        "nan_codes": [98],
    },
    "ASRCHKUP": {
        "zero_codes": [88],
        "nan_codes": [98, 99],
    },

    # anxiety/depression: number of days in last 2 weeks
    "ADPLEASR": {
        "zero_codes": [88],
        "nan_codes": [77, 99],
    },
    "ADDOWN": {
        "zero_codes": [88],
        "nan_codes": [77, 99],
    },
    "ADSLEEP": {
        "zero_codes": [88],
        "nan_codes": [77, 99],
    },
    "ADENERGY": {
        "zero_codes": [88],
        "nan_codes": [77, 99],
    },
    "ADEAT1": {
        "zero_codes": [88],
        "nan_codes": [77, 99],
    },
    "ADFAIL": {
        "zero_codes": [88],
        "nan_codes": [77, 99],
    },
    "ADTHINK": {
        "zero_codes": [88],
        "nan_codes": [77, 99],
    },
    "ADMOVE": {
        "zero_codes": [88],
        "nan_codes": [77, 99],
    },
}

In [36]:
x_num = x_train[:, numeric_idx].copy()

In [37]:
for k, feature_name in enumerate(numeric_names):
    col = x_num[:, k]

    if feature_name in numeric_rules:
        rule = numeric_rules[feature_name]

        col[np.isin(col, rule["zero_codes"])] = 0
        col[np.isin(col, rule["nan_codes"])] = np.nan

In [38]:
for k, name in enumerate(numeric_names):
    print(name, np.unique(x_num[:, k][~np.isnan(x_num[:, k])])[:20])

NUMADULT [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 14. 15. 18. 20.]
NUMMEN [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 18.]
NUMWOMEN [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
HHADULT [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 18. 20. 21.
 22. 23.]
PHYSHLTH [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
MENTHLTH [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
POORHLTH [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
NUMPHON2 [1. 2. 3. 4. 5. 6.]
CHILDREN [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 17. 18.
 20. 22.]
AVEDRNK2 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
DRNK3GE5 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
JOINPAIN [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
DOCTDIAB [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18.

In [39]:
def fit_mean_imputation(x):
    mean=np.nanmean(x,axis=0)
    x_new=np.where(np.isnan(x),mean,x)
    return x_new, mean

def transform_mean_imputation(x,mean):
    x_new=np.where(np.isnan(x),mean,x)
    return x_new

In [40]:
x_num_full,mean=fit_mean_imputation(x_num)

In [41]:
np.mean(np.isnan(x_num_full),axis=0)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [86]:
ordinal_rules = {
    "GENHLTH":  [7, 9],
    "CHECKUP1": [7, 9],
    "CHOLCHK":  [7, 9],
    "EDUCA":    [9],
    "INCOME2":  [77, 99],

    "SMOKDAY2": [7, 9],
    "LASTSMK2": [77, 99],

    "ARTHSOCL": [7, 9],
    "SEATBELT": [7, 9],

    "CRGVLNG1": [7, 9],
}

In [89]:
x_ord=x_train[:,ordinal_idx].copy()

for k, feature_name in enumerate(ordinal_names):
    if feature_name in ordinal_rules:
        x_ord[
            np.isin(x_ord[:, k], ordinal_rules[feature_name]),
            k
        ] = np.nan

In [91]:
x_ordinal_full,mean=fit_mean_imputation(x_ord)


In [92]:
np.mean(np.isnan(x_ordinal_full),axis=0)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [45]:
encoded_rules = {
    "ALCDAY5": {
        "zero_codes": [888],
        "nan_codes": [777, 999],
    },
    "FLSHTMY2": {
        "zero_codes": [],
        "nan_codes": [777777, 999999],
    },
    "ASACTLIM": {
        "zero_codes": [888],
        "nan_codes": [777, 999],
    },
    "HPVADSHT": {
        "zero_codes": [],
        "nan_codes": [77, 99],
    },
    "DROCDY3_": {
        "zero_codes": [],
        "nan_codes": [900],
    },
}

In [46]:
x_enc = x_train[:, encoded_numeric_idx].copy()

for k, feature_name in enumerate(encoded_numeric_names):

    if feature_name not in encoded_rules:
        continue

    rule = encoded_rules[feature_name]
    col = x_enc[:, k]

    col[np.isin(col, rule["zero_codes"])] = 0
    col[np.isin(col, rule["nan_codes"])] = np.nan

In [47]:
x_enc_full, enc_mean = fit_mean_imputation(x_enc)

In [94]:
X_proc = np.concatenate([x_one, x_num_full,x_ordinal_full, x_enc_full],axis=1)

In [95]:
X_proc.shape

(328135, 75)

In [96]:
from preprocessing.preprocess import train_val_split
x_proc_train,x_proc_val,y_proc_train,y_proc_val=train_val_split(X_proc,y_train,val_ratio=0.25)

In [97]:
x_proc_train.shape

(246102, 75)

In [98]:
from preprocessing.preprocess import fit_standardize,transform_standarize
x_proc_train_st,proc_mean,proc_std=fit_standardize(x_proc_train)
x_proc_val_st=transform_standarize(x_proc_val,proc_mean,proc_std)

In [99]:
x_proc_train_bias=np.c_[np.ones(x_proc_train.shape[0]),x_proc_train_st]
x_proc_val_bias=np.c_[np.ones(x_proc_val_st.shape[0]),x_proc_val_st]

In [100]:
def fit_standardize(x):
    centered_data = np.mean(x, axis=0)
    std=np.std(centered_data,axis=0)
    std_data = (x-centered_data) / std
    return std_data, centered_data, std

In [101]:
def ridge_regression(y, tx, lambda_):
    N=len(y)
    D=tx.shape[1]
    A=(tx.T@tx)+(2*N*lambda_*np.eye(D))
    b=tx.T@y
    w=np.linalg.solve(A,b)
    return w

In [102]:
w=ridge_regression(y_proc_train,x_proc_train_bias,lambda_=0.001)
y_pred=x_proc_val_bias@w


In [103]:
y_pred.mean()
print(y_pred.min())
print(y_pred.max())
print(np.percentile(y_pred, [50, 90, 95, 99, 99.9]))

-1.396159876126261
0.30327502301221665
[-0.84 -0.57 -0.48 -0.34 -0.2 ]


In [123]:
y_pred_class=np.where(y_pred>=-0.55,1,-1)

In [126]:
tp = np.sum((y_pred_class == 1) & (y_proc_val == 1))
tn = np.sum((y_pred_class == -1) & (y_proc_val == -1))
fp = np.sum((y_pred_class == 1) & (y_proc_val == -1))
fn = np.sum((y_pred_class == -1) & (y_proc_val == 1))

accuracy = (tp + tn) / len(y_proc_val)
precision = tp / (tp + fp) if (tp + fp) > 0 else 0
recall = tp / (tp + fn) if (tp + fn) > 0 else 0
f1 = (
    2 * precision * recall / (precision + recall)
    if (precision + recall) > 0
    else 0
)

print("TP:", tp)
print("TN:", tn)
print("FP:", fp)
print("FN:", fn)

print("accuracy :", accuracy)
print("precision:", precision)
print("recall   :", recall)
print("F1       :", f1)

TP: 2353
TN: 69884
FP: 4911
FN: 4885
accuracy : 0.8805846427657162
precision: 0.3239262114537445
recall   : 0.32508980381320807
F1       : 0.3245069645566129


In [114]:
feature_names[many_value]

array(['_STATE', 'IDATE', 'SEQNO', '_PSU', 'DIABAGE2', 'WEIGHT2',
       'HEIGHT3', 'MAXDRNKS', 'FRUITJU1', 'FRUIT1', 'FVBEANS', 'FVGREEN',
       'FVORANG', 'VEGETAB1', 'EXRACT11', 'EXEROFT1', 'EXERHMM1',
       'EXRACT21', 'EXEROFT2', 'EXERHMM2', 'STRENGTH', 'HIVTSTD3',
       'BLDSUGAR', 'FEETCHK2', 'LONGWTCH', 'ASTHMAGE', 'SCNTWRK1',
       'SCNTLWK1', '_STSTR', '_STRWT', '_WT2RAKE', '_CLLCPWT', '_DUALCOR',
       '_LLCPWT', '_AGE80', 'HTIN4', 'HTM4', 'WTKG3', '_BMI5', '_DRNKWEK',
       'FTJUDA1_', 'FRUTDA1_', 'BEANDAY_', 'GRENDAY_', 'ORNGDAY_',
       'VEGEDA1_', '_FRUTSUM', '_VEGESUM', 'MAXVO2_', 'FC60_', 'PADUR1_',
       'PADUR2_', 'PAFREQ1_', 'PAFREQ2_', '_MINAC11', '_MINAC21',
       'STRFREQ_', 'PAMIN11_', 'PAMIN21_', 'PA1MIN_', 'PAVIG11_',
       'PAVIG21_', 'PA1VIGM_'], dtype='<U8')

In [67]:
for i in many_value:
    column=x_train[:,i]
    value,count=np.unique(column,return_counts=True)
    missing_mask=np.isnan(column)
    missing_ratio=missing_mask.mean()
    print(value)
    print(count)
    print(missing_ratio)

[ 1.  2.  4.  5.  6.  8.  9. 10. 11. 12. 13. 15. 16. 17. 18. 19. 20. 21.
 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39.
 40. 41. 42. 44. 45. 46. 47. 48. 49. 50. 51. 53. 54. 55. 56. 66. 72.]
[ 5831  2736  5860  3905  9432 10065  8878  2982  2970  7241  3463  5324
  4287  3943  4430  4671 17383  6523  3541  6718  9343  6911  6636 12575
  4423  5432  4525 12959  2196  5233  8492  5047  9194  5005  3712  8841
  5133  3987  4269  4644  8557  5375  4414 10885  8428  4924  6438 11997
  4423  4568  4138  1213  4035]
0.0
[ 1012016.  1022015.  1022016.  1032015.  1032016.  1042015.  1042016.
  1052015.  1052016.  1062015.  1062016.  1072015.  1072016.  1082015.
  1082016.  1092015.  1092016.  1102015.  1102016.  1112015.  1112016.
  1122015.  1122016.  1132015.  1132016.  1142015.  1142016.  1152015.
  1152016.  1162015.  1162016.  1172015.  1172016.  1182015.  1182016.
  1192015.  1192016.  1202015.  1202016.  1212015.  1212016.  1222015.
  1222016.  1232015.  1232016.

In [68]:
for i in many_value:
    column = x_train[:, i]
    observed = column[~np.isnan(column)]

    print("feature:", feature_names[i])
    print("unique_count:", len(np.unique(observed)))
    print("min:", np.min(observed))
    print("max:", np.max(observed))
    print("mean:", np.mean(observed))
    print("std:", np.std(observed))
    print("missing_ratio:", np.isnan(column).mean())
    print()

feature: _STATE
unique_count: 53
min: 1.0
max: 72.0
mean: 29.973651088728726
std: 16.031752874847626
missing_ratio: 0.0

feature: IDATE
unique_count: 414
min: 1012016.0
max: 12312015.0
mean: 6563638.198147104
std: 3489242.351508263
missing_ratio: 0.0

feature: SEQNO
unique_count: 21780
min: 2015000001.0
max: 2015023235.0
mean: 2015005197.3278103
std: 4118.469112439105
missing_ratio: 0.0

feature: _PSU
unique_count: 21780
min: 2015000001.0
max: 2015023235.0
mean: 2015005197.3278103
std: 4118.469112439105
missing_ratio: 0.0

feature: DIABAGE2
unique_count: 98
min: 1.0
max: 99.0
mean: 54.47468024632875
std: 18.21646639369587
missing_ratio: 0.8713334450759596

feature: WEIGHT2
unique_count: 550
min: 50.0
max: 9999.0
mean: 735.0221660821311
std: 2200.8790007025927
missing_ratio: 0.012025538269309887

feature: HEIGHT3
unique_count: 142
min: 205.0
max: 9999.0
mean: 739.0984530222903
std: 1371.2135137455202
missing_ratio: 0.013430447833970774

feature: MAXDRNKS
unique_count: 58
min: 1.0
max: 9

From now I delete features that has empty values and simple baseline.

In [69]:
complete_mask = ~np.isnan(x_train).any(axis=1)

print("remaining rows:", complete_mask.sum())
print("remaining ratio:", complete_mask.mean())

remaining rows: 0
remaining ratio: 0.0


In [70]:
complete_feature_mask = ~np.isnan(x_train).any(axis=0)

print("remaining features:", complete_feature_mask.sum())
print("remaining ratio:", complete_feature_mask.mean())

remaining features: 82
remaining ratio: 0.2554517133956386


In [71]:
complete_feature_mask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False,  True,  True, False, False, False, False,
        True, False, False,  True,  True, False, False,  True,  True,
       False,  True,  True, False, False,  True,  True,  True,  True,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [72]:
feature_names[complete_feature_mask]

array(['_STATE', 'FMONTH', 'IDATE', 'IMONTH', 'IDAY', 'IYEAR', 'DISPCODE',
       'SEQNO', '_PSU', 'MENTHLTH', 'HLTHPLN1', 'PERSDOC2', 'BLOODCHO',
       'CVDSTRK3', 'ASTHMA3', 'CHCOCNCR', 'CHCCOPD1', 'ADDEPEV2',
       'CHCKIDNY', 'SEX', 'MARITAL', 'EDUCA', 'RENTHOM1', 'EMPLOY1',
       'QSTVER', '_STSTR', '_RAWRAKE', '_WT2RAKE', '_DUALUSE', '_LLCPWT',
       '_RFHLTH', '_HCVU651', '_RFHYPE5', '_CHOLCHK', '_LTASTH1',
       '_CASTHM1', '_ASTHMS1', '_PRACE1', '_MRACE1', '_HISPANC', '_RACE',
       '_RACEG21', '_RACEGR3', '_AGEG5YR', '_AGE65YR', '_AGE80', '_AGE_G',
       '_RFBMI5', '_CHLDCNT', '_EDUCAG', '_INCOMG', '_SMOKER3',
       '_RFSMOK3', 'DRNKANY5', 'DROCDY3_', '_RFBING5', '_DRNKWEK',
       '_RFDRHV5', '_MISFRTN', '_MISVEGN', '_FRTRESP', '_VEGRESP',
       '_FRTLT1', '_VEGLT1', '_FRT16', '_VEG23', '_FRUITEX', '_VEGETEX',
       '_TOTINDA', 'MAXVO2_', 'FC60_', 'PAMISS1_', '_PACAT1', '_PAINDX1',
       '_PA150R2', '_PA300R2', '_PA30021', '_PASTRNG', '_PAREC1',
       '_PASTAE1',

In [73]:
complete_idx = np.where(complete_feature_mask)[0]

for i in complete_idx:
    print(
        feature_names[i],
        unique_counts[i]
    )

_STATE 53
FMONTH 12
IDATE 414
IMONTH 12
IDAY 31
IYEAR 2
DISPCODE 2
SEQNO 21780
_PSU 21780
MENTHLTH 33
HLTHPLN1 4
PERSDOC2 5
BLOODCHO 4
CVDSTRK3 4
ASTHMA3 4
CHCOCNCR 4
CHCCOPD1 4
ADDEPEV2 4
CHCKIDNY 4
SEX 2
MARITAL 7
EDUCA 7
RENTHOM1 5
EMPLOY1 9
QSTVER 8
_STSTR 1306
_RAWRAKE 12
_WT2RAKE 5528
_DUALUSE 3
_LLCPWT 216913
_RFHLTH 3
_HCVU651 3
_RFHYPE5 3
_CHOLCHK 4
_LTASTH1 3
_CASTHM1 3
_ASTHMS1 4
_PRACE1 10
_MRACE1 9
_HISPANC 3
_RACE 9
_RACEG21 3
_RACEGR3 6
_AGEG5YR 14
_AGE65YR 3
_AGE80 63
_AGE_G 6
_RFBMI5 3
_CHLDCNT 7
_EDUCAG 5
_INCOMG 6
_SMOKER3 5
_RFSMOK3 3
DRNKANY5 4
DROCDY3_ 36
_RFBING5 3
_DRNKWEK 237
_RFDRHV5 3
_MISFRTN 3
_MISVEGN 5
_FRTRESP 2
_VEGRESP 2
_FRTLT1 3
_VEGLT1 3
_FRT16 2
_VEG23 2
_FRUITEX 3
_VEGETEX 3
_TOTINDA 3
MAXVO2_ 163
FC60_ 156
PAMISS1_ 3
_PACAT1 5
_PAINDX1 3
_PA150R2 4
_PA300R2 4
_PA30021 3
_PASTRNG 3
_PAREC1 5
_PASTAE1 3
_RFSEAT2 3
_RFSEAT3 3


In [74]:
x_base=x_train[:,complete_feature_mask]

In [75]:
np.isnan(x_base).mean()

np.float64(0.0)

In [76]:
from preprocessing.preprocess import train_val_split
x_base_train,x_val,y_base_train,y_val=train_val_split(x_base,y_train,val_ratio=0.25)
print(np.isnan(x_base_train).any())
print(np.sum(np.std(x_base_train, axis=0) == 0))
print(np.linalg.matrix_rank(x_base_train), x_base_train.shape[1])

False
0
64 82


In [77]:
def fit_standardize(x):
    centered_data = np.mean(x, axis=0)
    std=np.std(x,axis=0)
    std[std == 0] = 1
    std_data = (x-centered_data) / std
    return std_data, centered_data, std

In [78]:
def transform_standarize(x,centered_data,std):
    return (x-centered_data)/std

In [79]:
x_base_stand,center,std=fit_standardize(x_base_train)
x_val_stand=transform_standarize(x_val,center,std)

In [80]:
x_base_bias=np.c_[np.ones(x_base_stand.shape[0]),x_base_stand]
x_val_bias=np.c_[np.ones(x_val_stand.shape[0]),x_val_stand]

In [81]:
def ridge_regression(y, tx, lambda_):
    N=len(y)
    D=tx.shape[1]
    A=(tx.T@tx)+(2*N*lambda_*np.eye(D))
    b=tx.T@y
    w=np.linalg.solve(A,b)
    return w

In [82]:

w=ridge_regression(y_base_train,x_base_stand,lambda_=0)
y_pred=x_val_stand@w



In [83]:
np.unique(y_pred,return_counts=True)

(array([-0.83, -0.83, -0.83, ...,  1.33,  1.37,  1.61], shape=(9349,)),
 array([1, 1, 1, ..., 1, 1, 1], shape=(9349,)))

In [84]:
y_pred_class=np.where(y_pred>=0.3,1,-1)
(y_pred_class == y_val).mean()

np.float64(0.8896419733521875)

In [85]:
tp = np.sum((y_pred_class == 1) & (y_val == 1))
tn = np.sum((y_pred_class == -1) & (y_val == -1))
fp = np.sum((y_pred_class == 1) & (y_val == -1))
fn = np.sum((y_pred_class == -1) & (y_val == 1))

accuracy = (tp + tn) / len(y_val)
precision = tp / (tp + fp) if (tp + fp) > 0 else 0
recall = tp / (tp + fn) if (tp + fn) > 0 else 0
f1 = (
    2 * precision * recall / (precision + recall)
    if (precision + recall) > 0
    else 0
)

print("TP:", tp)
print("TN:", tn)
print("FP:", fp)
print("FN:", fn)

print("accuracy :", accuracy)
print("precision:", precision)
print("recall   :", recall)
print("F1       :", f1)

TP: 2373
TN: 70607
FP: 4188
FN: 4865
accuracy : 0.8896419733521875
precision: 0.3616826703246456
recall   : 0.327852998065764
F1       : 0.34393796651931297
